CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    username    VARCHAR(50),
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255),
    enabled     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_b1906ae7a05077a50ac196a24 UNIQUE (provider, provider_id);